### ISSUE TITLE
FBX importer cant't get phase features 

### ISSUE THREAD

**Issue by tucker666** [pauzii/PhaseBetweener#17]
hello, I'm trying to use my own data for training. I notice that there is a FBX importer in header AI4Animation/importer.
 When I import my fbx files in unity, the actor moves normally . but as i follow the instructions to extract features, i can't get the deep phase features while other features are correct. i want to know how to get deep phase features.
Or, I can't transfer my fbx files to  correct bvh files like lafan1. when i import my bvh files, the mesh of the actor looks strange. Is there any instruction about how to get correct bvh format?

[test.fbx.zip](https://github.com/paulstarke/PhaseBetweener/files/14850276/test.fbx.zip)

**Comment by paulstarke** [comment]
Hi @tucker666!

The fbx/bvh importer only transforms the data into a MotionAsset format that Unity can better understand. Using your own motion data and custom skeleton is not so easy and requires to rewrite parts of the code for data processing, data export, training as well as runtime control. In order to obtain the deep phase features for you motion data you need to train your data with the Periodic Autoencoder.
