### ISSUE TITLE
Bone Velocities in Target State included in the input tensor?

### ISSUE THREAD

**Issue by UnrealXinda** [pauzii/PhaseBetweener#18]
Hi, first off, thanks for the awesome work! I was reading the input part and am having some troubles understanding the discrepancy between the paper and the sample code. Basically, per the paper, the target state consists of only the target pose's bone positions and rotations. However, in InBetweeningController.cs line 374, I'm seeing that the input pose's bone velocities are also included as the input, which makes the variables of target state the same as character state. I'm wondering what is going on here. Thanks

**Comment by paulstarke** [comment]
Hi @UnrealXinda. Thanks for noticing! Unfortunately I don't have the model without velocity input anymore but you can easily reproduce it and get the same results as in the paper.

In the code demo we're sampling reference poses from the lafan motion capture dataset and thus can provide velocities for the target state. However, if you can't provide them during runtime because you're defining the target pose manually, you can retrain the model without velocity features. To do so remove the velocity input when exporting training data as well as in the runtime controller and follow the steps in the code readme.

This will produce the same model as described in the paper. Hope this helps!

**Comment by UnrealXinda** [comment]
Oh I see, so this is optional. Yeah it makes sense to include the velocities in the target pose if you already have that info so it can provide better results. Thanks for the explanation!
